import Font from './font';

const size = {
  verySmall: Font.res8,
  small: Font.res16,
  normal: Font.res24,
  big: Font.res30,
  veryBig: Font.res40,
};

/**
 * this is icon declare in logivan driver project
 * using ico-moon
 */
const logivanIcon = {
  exclamation: 'exclamation',
  checkMarkCircle: 'checkmark- circle',
  chevronRight: 'chevron-right',
  arrowDownCircle: 'arrow-down-circle',
  arrowDown: 'arrow-down',
  arrowUpCircle: 'arrow-up-circle',
  arrowUp: 'arrow-up',
  calendar: 'calendar',
  clock: 'clock',
  documentChecked: 'document-checked',
  document: 'document',
  headphone: 'headphone',
  leftArrow: 'left-arrow',
  order: 'order',
  package2: 'package-2',
  phoneChatting: 'phone-chatting',
  pinMap: 'pin-map',
  rightArrow: 'right-arrow',
  truckRunning: 'truck-running',
  searchInPage: 'search-in-page',
  bellAlert: 'bell-alert',
  package: 'package',
  truck: 'truck',
  currentLocation: 'current-location',
};

const ionIcons = {
  mdAdd: 'md-add',
  iosTrash: 'trash',
  mdPlay: 'md-play',
  mdSync: 'md-sync',
  iosEye: 'ios-eye',
  iosTrending: 'ios-trending',
  iosTrendingUp: 'ios-trending-up',
  mdTrending: 'md-trending',
  mdTrendingUp: 'md-trending-up',
  mdPause: 'md-pause',
  iosStar: 'ios-star',
  mdClose: 'md-close',
  iosLock: 'ios-lock',
  iosHelpCircle: 'ios-help-circle',
  mdHelpCircle: 'md-help-circle',
  mdAlert: 'md-alert',
  iosMail: 'ios-mail',
  mdHeart: 'md-heart',
  iosClose: 'ios-close',
  iosFlash: 'ios-flash',
  mdCamera: 'md-camera',
  iosHeart: 'ios-heart',
  iosSearch: 'ios-search',
  iosPerson: 'ios-person',
  iosCamera: 'ios-camera',
  iosEyeOff: 'ios-eye-off',
  iosRefresh: 'ios-refresh',
  iosGlasses: 'ios-glasses',
  mdCheckBox: 'md-checkbox',
  iosArrowUp: 'ios-arrow-up',
  mdCheckmark: 'md-checkmark',
  iosCheckMark: 'ios-checkmark',
  iosArrowBack: 'ios-arrow-back',
  iosArrowRoundBack: 'ios-arrow-round-back',
  iosArrowDown: 'ios-arrow-down',
  mdCloseCircle: 'md-close-circle',
  iosBookOutline: 'ios-book-outline',
  iosFlagOutline: 'ios-flag-outline',
  iosCloseCircle: 'ios-close-circle',
  iosMenuOutline: 'ios-menu-outline',
  iosLockOutline: 'ios-lock-outline',
  iosStarOutline: 'ios-star-outline',
  iosPaperPlane: 'ios-paper-plane',
  iosTimerOutline: 'ios-timer-outline',
  iosHeartOutline: 'ios-heart-outline',
  iosTrashOutline: 'ios-trash-outline',
  iosAlertOutline: 'ios-alert-outline',
  iosCloseOutline: 'ios-close-outline',
  iosArrowForward: 'ios-arrow-forward',
  iosSearchOutline: 'ios-search-outline',
  iosContactOutline: 'ios-contact-outline',
  iosOptionsOutline: 'ios-options-outline',
  mdCheckmarkCircle: 'md-checkmark-circle',
  iosSettingsOutline: 'ios-settings-outline',
  iosCheckmarkCircle: 'ios-checkmark-circle',
  iosArrowBackOutline: 'ios-arrow-back-outline',
  iosHelpCircleOutline: 'ios-help-circle-outline',
  iosInfoOutline: 'ios-information-circle-outline',
  iosCloseCircleOutline: 'ios-close-circle-outline',
  iosArrowForwardOutline: 'ios-arrow-forward-outline',
  iosCloudDownloadOutline: 'ios-cloud-download-outline',
  mdCheckmarkCircleOutline: 'md-checkmark-circle-outline',
  iosWarningOutline: 'ios-warning-outline',
  iosSunnyOutline: 'ios-sunny-outline',
};

const Icon = {
  size,
  logivan: logivanIcon,
  ion: ionIcons,
};

export default Icon;
