export const MODAL_NAMES = {
  /**
   * @COMMON
   */
  COMMON: {
    MODAL_ALERT: 'MODAL_ALERT',
    MODAL_LOTTIE: 'MODAL_LOTTIE',
    MODAL_LOADING: 'MODAL_LOADING',
    MODAL_CONGRATS: 'MODAL_CONGRATS',
    MODAL_IMAGE_VIEWER: 'MODAL_IMAGE_VIEWER',
    MODAL_SIGN_UP_SUCCESS: 'MODAL_SIGN_UP_SUCCESS',
  },
  /**
   * @NOTIFICATION
   */
  NOTIFICATION: {
    POPUP: 'NOTIFICATION_POPUP',
  },
  /**
   * @FEATURE
   */
  FEATURE: {},
};
